spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:8812/qdb
    username: admin
    password: quest
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    defer-datasource-initialization: true