CREATE TABLE IF NOT EXISTS averages (
	channel_id SYMBOL CAPACITY 256 CACHE INDEX CAPACITY 256,
	value DOUBLE,
	timestamp TIMESTAMP
) TIMESTAMP (timestamp) PARTITION BY DAY WAL;

CREATE TABLE IF NOT EXISTS channels (
	id SYMBOL CAPACITY 256 CACHE INDEX CAPACITY 256,
	alias STRING,
	unit STRING,
	max_value INT
);

CREATE TABLE IF NOT EXISTS events (
	channel_id SYMBOL CAPACITY 256 CACHE INDEX CAPACITY 256,
	alarm_level SHORT,
	timestamp TIMESTAMP
) TIMESTAMP (timestamp) PARTITION BY DAY WAL;

CREATE TABLE IF NOT EXISTS layout (
	channel_id SYMBOL CAPACITY 256 CACHE INDEX CAPACITY 256,
	page SHORT,
	offset SHORT,
	span SHORT
);

CREATE TABLE IF NOT EXISTS limits (
	channel_id SYMBOL CAPACITY 256 CACHE INDEX CAPACITY 256,
	alarm_level SHORT,
	value DOUBLE,
	timestamp TIMESTAMP
) timestamp (timestamp);